filebeat.registry_file: /usr/share/filebeat/data/registry


filebeat.config.inputs:
  path: ${path.config}/prospectors.d/*.yml
  reload.enabled: false


xpack.monitoring.enabled: true


output.elasticsearch:
  hosts: ["elasticsearch:9200"]


logging.to_files: false


setup:
  kibana.host: "kibana:5601"
  dashboards.enabled: true
